<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>edu.remad</groupId>
	<artifactId>ical4j-builder-tutor3</artifactId>
	<version>3.1.1-SNAPSHOT</version>
	<name>ical4j-builder-tutor3</name>
	<description>Java 17 project creates ICalendar files</description>

	<properties>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.version>3.15.0</maven.compiler.version>
		<maven.jar.version>3.5.0</maven.jar.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<junit5.version>5.14.2</junit5.version>
		<library.author>ReMad</library.author>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.mnode.ical4j</groupId>
			<artifactId>ical4j</artifactId>
			<version>4.2.5</version>
		</dependency>

		<!-- Maven Plugins -->
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>${maven.compiler.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-jar-plugin</artifactId>
			<version>${maven.jar.version}</version>
		</dependency>

		<!-- own implementations -->
		<dependency>
			<groupId>edu.remad</groupId>
			<artifactId>tutoring3-models</artifactId>
			<version>0.60.2-SNAPSHOT</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>ical4j-builder-tutor3</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.version}</version>
				<configuration>
					<encoding>${project.build.sourceEncoding}</encoding>
					<source>${maven.compiler.target}</source>
					<target>${maven.compiler.source}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>${maven.jar.version}</version>
				<configuration>
					<archive>
						<manifest>
							<addClasspath>true</addClasspath>
							<mainClass>
								edu.remad.ical4jbuilder.builders.InterchangeCalendarBuilderExample</mainClass>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
						<manifestEntries>
							<mode>production</mode>
							<Built-By>${library.author}</Built-By>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>